# ------------------------------------------
# Configuration
# ------------------------------------------

title: mlgrto.com
author: Carlos Melegrito
description: Carlos Melegrito is a designer studying Computer Science

url: http://mlgrto.com
icon: /static/images/favicon.ico
color: CFA352
twitter: cjmlgrto
contact: mailto:cj@mlgrto.com

permalink: /blog/:year/:title/
markdown: kramdown

sections:
  blog: /
  work: /work/
  info: /info/

sass:
  sass_style: compressed

exclude:
- .env
- .gitignore
- Rakefile
- Gemfile
- Gemfile.lock
- README.md
- s3_website.yml

collections:
  posts:
    title: Posts
    output: true
  drafts:
    title: Drafts
    output: true
  projects:
    title: Projects
    output: true

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: page
    type: blog
    title: null
    image: null
    preview: null
    style: null
    link: null
- scope:
    path: ""
    type: drafts
  values:
    layout: page
    type: blog
    title: null
    image: null
    preview: null
    style: null
    link: null
    permalink: /draft/:year/:title/
- scope:
    path: ""
    type: projects
  values:
    layout: page
    type: work
    title: null
    image: null
    preview: null
    style: null
    link: null